### ISSUE TITLE
Flickr to Google+ transfers only the first 500 pictures in the album, not the entire album

### ISSUE THREAD

**Issue by getutsav** [vickyg3/social-photos#61] opened 2016-06-26 20:52 UTC
I tried to transfer an album containing 1200 photos from my Flickr account to Google+ but it transferred only the first 500 images contained in the album not the entire one.

How can I get around this issue ?

**Comment by vickyg3** [comment] 2016-07-21 17:36
Duplicate of #53.

**Closed by vickyg3** 2016-07-21 17:36 UTC
Labels: bug
