### ISSUE TITLE
Google Photos to Facebook error in Photos

### ISSUE THREAD

**Issue by leighhobson89** [vickyg3/social-photos#66] opened 2017-01-16 20:09 UTC
After copying a full album by drg and drop from google photos to facebook, I noticed that from 110 photos copied, that 43 of them were incomplete, meaning that half of the image was just a grey block.  I deleted them all before reporting this issue so i dont have a screenshot, but surely this must have already been reported, so I am adding my 2 cents to it.

**Comment by qwandor** [comment] 2017-01-23 11:49
I get the same issue. Looks like https://github.com/vickyg3/social-photos/issues/67 and https://github.com/vickyg3/social-photos/issues/65 are the same too. I don't get the issue when I set up social-photos on my own server, so probably the issue is with server config rather than the code itself, though I did have to make a few code changes to get it running with a newer version of PHP at all.

**Comment by vickyg3** [comment] 2017-01-23 22:37
@qwandor based on a quick look on the server, everything looks fine. so i'm not sure what the problem is. what's the php version on your trials?

**Comment by qwandor** [comment] 2017-01-23 22:45
I've got PHP 5.6.29+dfsg-0+deb8u1. I wonder if there could also be some configuration issue? Maybe some limit on the size of uploads or downloads?

**Comment by vickyg3** [comment] 2017-01-23 22:48
Hmm, my php version seems to be 5.3.10. May be that's the problem. I'll see if i can upgrade.

> Maybe some limit on the size of uploads or downloads?

Nothing has changed on those fronts. So i don't know why this would happen all of a sudden.

**Comment by qwandor** [comment] 2017-01-23 22:50
Has your memory_limit setting changed by any chance? I wonder if that might limit the size of downloads.

**Comment by vickyg3** [comment] 2017-01-23 22:53
It is set at 128M. Not changed since 2014.

**Comment by firebird7102** [comment] 2017-01-30 11:23
I just wrote a comment about this before finding this thread. What was achieved/decided about this 7 days ago? Only 3 out of my 101 photos were not corrupted when I just tried to upload from google photos to facebook album (the files are probably large as taken on SLR rather than smartphone). Could this be the reason? Is there any ability to increase file size limit? (Great capability btw! Thank you for sharing)
<img width="215" alt="screen shot 2017-01-30 at 10 10 15 pm" src="https://cloud.githubusercontent.com/assets/25431044/22421331/a6b257fe-e73a-11e6-9f4b-94369459ac11.png">

**Comment by vickyg3** [comment] 2017-01-30 17:57
Hi all, I'm sorry i haven't had the time to look into this issue. Any suggestions that i can quickly try out are welcome. If not, i'm going to need some time to dig into this myself. Sorry!

**Comment by vickyg3** [comment] 2017-02-14 19:41
Can one of you please try if this issue happens now? I have increased the disk space on my server. It seems to work fine for the few transfers that i tried. Thanks!

@firebird7102 @qwandor @leighhobson89

**Comment by qwandor** [comment] 2017-02-14 23:34
It seems fine for me so far, I'll report if I have any further trouble with it.

**Comment by toralux** [comment] 2017-02-15 08:49
Works like a charm now - thanks! :):)

**Comment by vickyg3** [comment] 2017-02-17 18:04
Thanks folks! I'm closing this issue for now. Please re-open if it happens again.

**Closed as completed by vickyg3** 2017-02-17 18:04 UTC
